import "./globals.css";
import SparklesIcon from "@/components/SparklesIcon";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-b from-purple-700 to-pink-500 min-h-screen text-white dark:bg-gray-800 dark:text-gray-300 transition-all`}>
        <main className="p-4 max-w-screen-xl mx-auto">
          <header className="flex justify-between items-center my-4 sm:my-8">
            <Link href="/" className="flex items-center gap-2">
              <SparklesIcon />
              <span className="text-xl font-semibold">CaptionWave</span>
            </Link>
            <nav className="flex items-center gap-4 text-white/80 text-sm sm:text-base">
              <Link href="/" className="hover:text-white">Home</Link>
              <Link href="/pricing" className="hover:text-white">Pricing</Link>
              <a href="mailto:chandresh.beas@gmail.com" className="hover:text-white">Contact</a>
            </nav>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
